require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'example2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'zabo-sdk-react-native', :path => '../..'

  target 'example2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'example2-tvOS' do
  # Pods for example2-tvOS

  target 'example2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
